name: test_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  intl: ^0.18.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Black.ttf
        - weight: 800
        - asset: assets/fonts/Gilroy-Bold.ttf
        - weight: 800
        - asset: assets/fonts/Gilroy-Light.ttf
        - weight: 300
        - asset: assets/fonts/Gilroy-Medium.ttf
        - weight: 500
        - asset: assets/fonts/Gilroy-Regular.ttf
        - weight: 400
